default:
  mysql: root:root@tcp(localhost:3308)/test
  redis: localhost:6379:0
  rabbitMQ:
    server: amqp://rabbitmq_user:rabbitmq_password@localhost:5672/
    queues:
      - name: test
        prefetchCount: 1
      - name: test2
        prefetchCount: 1
        router: test
        delayed: false
        autodelete: false
        router_keys:
          - aa
          - bb
    routers:
      - name: test
        type: fanout
  localCache: 1000
  lazyQueueRedis: default_queue
  lazyQueueRabbitMQ: test2
  dirtyQueueRedis: default_queue
  dirtyQueueRabbitMQ: test2
  logQueueRedis: default_queue
  logQueueRabbitMQ: test2
  locker: default
default_queue:
  redis: localhost:6379:1
