default:
  mysql: root:root@tcp(localhost:3308)/test
  redis: localhost:6379:0
  rabbitMQ:
    server: amqp://rabbitmq_user:rabbitmq_password@localhost:5672/
    queues:
      - name: test
        passive: false
        durrable: false
        exclusive: false
        autodelete: false
        nowait: false
        prefetchCount: 1
        prefetchSize: 0
      - name: test2
        passive: false
        durrable: false
        exclusive: false
        autodelete: false
        nowait: false
        prefetchCount: 1
        prefetchSize: 0
    exchanges:
      - name: test
        type: fanout
        durable: false
        autodelete: false
        internal: false
        nowait: false
  localCache: 1000
  lazyQueue: default_queue
  dirtyQueue: default_queue
  logQueue: default_queue
  locker: default
default_queue:
  redis: localhost:6379:1
